# Build script for mouseExperiment package
library(devtools)

# Clean up old artifacts
if (file.exists("NAMESPACE")) {
  cat("Removing old NAMESPACE file\n")
  file.remove("NAMESPACE")
}

# Create NAMESPACE with proper exports
cat("# Generated by the build.R script\n\n", file = "NAMESPACE")

# Add all standard roxygen2 exports
cat("
export(analyze_drug_synergy)
export(analyze_drug_synergy_over_time)
export(calculate_dates)
export(calculate_volume)
export(dose_response_statistics)
export(forest_plot)
export(plot_auc)
export(plot_caterpillar)
export(plot_combination_index)
export(plot_drug_synergy)
export(plot_survival)
export(plot_synergy_combined)
export(plot_synergy_trend)
export(plot_treatments)
export(plot_tumor_growth)
export(post_power_analysis)
export(survival_statistics)
export(tumor_auc_analysis)
export(tumor_growth_statistics)
", file = "NAMESPACE", append = TRUE)

# Add all imports
cat("
import(dplyr)
import(drc)
import(ggplot2)
import(stats)
import(survival)
import(survminer)
importFrom(clinfun,jonckheere.test)
importFrom(dplyr,\"%>%\")
importFrom(dplyr,arrange)
importFrom(dplyr,filter)
importFrom(dplyr,group_by)
importFrom(dplyr,mutate)
importFrom(dplyr,summarize)
importFrom(ggplot2,aes)
importFrom(ggplot2,element_text)
importFrom(ggplot2,geom_bar)
importFrom(ggplot2,geom_boxplot)
importFrom(ggplot2,geom_errorbar)
importFrom(ggplot2,geom_jitter)
importFrom(ggplot2,geom_point)
importFrom(ggplot2,ggplot)
importFrom(ggplot2,ggtitle)
importFrom(ggplot2,labs)
importFrom(ggplot2,scale_color_manual)
importFrom(ggplot2,scale_fill_manual)
importFrom(ggplot2,theme)
importFrom(ggplot2,theme_classic)
importFrom(ggplot2,theme_minimal)
importFrom(ggpubr,ggarrange)
importFrom(rlang,\"!!\")
importFrom(rlang,sym)
importFrom(stats,TukeyHSD)
importFrom(stats,aov)
importFrom(stats,as.formula)
importFrom(stats,confint)
importFrom(stats,model.matrix)
importFrom(stats,pchisq)
importFrom(stats,power.t.test)
importFrom(stats,t.test)
importFrom(survival,Surv)
importFrom(survival,coxph)
importFrom(survival,survdiff)
importFrom(survival,survfit)
importFrom(utils,head)
importFrom(utils,tail)
", file = "NAMESPACE", append = TRUE)

# Manually add exports for the data objects
cat("Ensuring datasets are properly exported in the package\n")

# Clean and rebuild data directory
system("Rscript data-raw/create_datasets.R")

# Add data exports directly to NAMESPACE
cat("
# Exported datasets
export(combo_treatment_schedule)
export(combo_treatment_synthetic_data)
export(dose_levels_synthetic_data)
export(dose_levels_treatment_schedule)
export(my_data)
export(synthetic_data)
", file = "NAMESPACE", append = TRUE)

# Build and install the package
cat("Building and installing the package...\n")
devtools::build()
install.packages(list.files(pattern = "mouseExperiment_.*\\.tar\\.gz", full.names = TRUE), repos = NULL, type = "source")

cat("Package build and installation complete.\n") 